prompt Gather Table Statistics for table &1....
exec dbms_stats.gather_table_stats(  upper('&1'),upper('&2'), null, method_opt=>'FOR TABLE FOR ALL COLUMNS SIZE REPEAT',estimate_percent =>4, cascade=>true, no_invalidate=>false);
